/*
 * FPGrowth.java
 *
 * Created on __DATE__, __TIME__
 */

//import com.logic.Tools;

/**
 * 
 * @author __USER__
 */
public class AngelImpl extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form FPGrowth
	 * 
	 * @param fpg
	 */
	Tools fpg;

	public AngelImpl(Tools fpg) {
		this.fpg = fpg;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jtaShowMining = new javax.swing.JTextArea();
		jLabel2 = new javax.swing.JLabel();
		txtNoofFreqSets = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jtaAsso = new javax.swing.JTextArea();
		btnShowMining = new javax.swing.JButton();
		btnExit = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(null);

		jtaShowMining.setColumns(20);
		jtaShowMining.setRows(5);
		jScrollPane1.setViewportView(jtaShowMining);

		getContentPane().add(jScrollPane1);
		jScrollPane1.setBounds(30, 40, 420, 100);

		jLabel2.setText("No.of Buckets :");
		getContentPane().add(jLabel2);
		jLabel2.setBounds(30, 150, 110, 20);
		getContentPane().add(txtNoofFreqSets);
		txtNoofFreqSets.setBounds(140, 150, 160, 20);

		jLabel3.setText("Generalized Table :");
		getContentPane().add(jLabel3);
		jLabel3.setBounds(30, 190, 200, 14);

		jtaAsso.setColumns(20);
		jtaAsso.setRows(5);
		jScrollPane2.setViewportView(jtaAsso);

		getContentPane().add(jScrollPane2);
		jScrollPane2.setBounds(30, 210, 420, 220);

		btnShowMining.setText("Show Generalization");
		btnShowMining.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnShowMiningActionPerformed(evt);
			}
		});
		getContentPane().add(btnShowMining);
		btnShowMining.setBounds(130, 10, 200, 23);

		btnExit.setText("Exit");
		btnExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExitActionPerformed(evt);
			}
		});
		getContentPane().add(btnExit);
		btnExit.setBounds(363, 440, 90, 23);

		jtaAsso.setEditable(false);
		jtaShowMining.setEditable(false);
		txtNoofFreqSets.setEditable(false);

		setSize(500, 520);
		setTitle("Angelization::");
		setResizable(false);
		setVisible(true);
	}// </editor-fold>

	// GEN-END:initComponents

	private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void btnShowMiningActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		fpg.mining(this);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnExit;
	private javax.swing.JButton btnShowMining;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	public javax.swing.JTextArea jtaAsso;
	public javax.swing.JTextArea jtaShowMining;
	public javax.swing.JTextField txtNoofFreqSets;
	// End of variables declaration//GEN-END:variables

}