/*
 * Home.java
 *
 * Created on __DATE__, __TIME__
 */



import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

//import com.logic.Tools;

/**
 *
 * @author  __USER__
 */
public class AngelGUI extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form Home */
	public AngelGUI() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtDataset = new javax.swing.JTextField();
		btnShowItems = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jtaItems = new javax.swing.JTextArea();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jtaFPDetails = new javax.swing.JTextArea();
		btnStartMining = new javax.swing.JButton();
		btnExit = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(null);

		jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18));
		jLabel1.setForeground(new java.awt.Color(102, 51, 255));
		jLabel1.setText("ANGEL");
		getContentPane().add(jLabel1);
		jLabel1.setBounds(200, 0, 460, 30);

		jLabel2.setText("Data Set :");
		getContentPane().add(jLabel2);
		jLabel2.setBounds(20, 60, 60, 20);
		getContentPane().add(txtDataset);
		txtDataset.setBounds(80, 60, 300, 20);

		btnShowItems.setText("Show Items");
		btnShowItems.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnShowItemsActionPerformed(evt);
			}
		});
		getContentPane().add(btnShowItems);
		btnShowItems.setBounds(390, 60, 130, 23);

		jtaItems.setColumns(20);
		jtaItems.setRows(5);
		jScrollPane1.setViewportView(jtaItems);

		getContentPane().add(jScrollPane1);
		jScrollPane1.setBounds(80, 90, 440, 130);

		jLabel3.setText("Data Storage :");
		getContentPane().add(jLabel3);
		jLabel3.setBounds(80, 230, 100, 14);

		jtaFPDetails.setColumns(20);
		jtaFPDetails.setRows(5);
		jScrollPane2.setViewportView(jtaFPDetails);

		getContentPane().add(jScrollPane2);
		jScrollPane2.setBounds(80, 250, 440, 96);

		btnStartMining.setText("Start Mining");
		btnStartMining.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnStartMiningActionPerformed(evt);
			}
		});
		getContentPane().add(btnStartMining);
		btnStartMining.setBounds(80, 360, 150, 30);

		btnExit.setText("Exit");
		btnExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExitActionPerformed(evt);
			}
		});
		getContentPane().add(btnExit);
		btnExit.setBounds(240, 360, 90, 30);
		jtaFPDetails.setEditable(false);
		jtaItems.setEditable(false);
		txtDataset.setEditable(false);
		
		setSize(550, 450);
		setTitle("ANGEL::");
		setResizable(false);
		setVisible(true);
	}

	private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void btnStartMiningActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		datafile="-F"+datafile;
		String[] ag={datafile,"-S2.5", "-C90"};
		fpg=new Tools();
		fpg.init(this,ag);
		int i=JOptionPane.showConfirmDialog(null, "Start Mining?");
		if(i==0){
			new AngelImpl(fpg);
		}else{
			System.out.println("N");
		}
	}
	String datafile;
	Tools fpg;
	private void btnShowItemsActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		datafile="Microdata.num";
		txtDataset.setText(datafile);
		
		try {
			FileInputStream fis=new FileInputStream(datafile);
			byte[] b=new byte[fis.available()];
			fis.read(b);
			fis.close();
			String str=new String(b);
			jtaItems.setText(str);
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

	public static void main(String args[]) {
		try {
			String inf = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";

			UIManager.setLookAndFeel(inf);

		} catch (Exception e) {
			e.printStackTrace();
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AngelGUI().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnExit;
	private javax.swing.JButton btnShowItems;
	private javax.swing.JButton btnStartMining;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	public javax.swing.JTextArea jtaFPDetails;
	public javax.swing.JTextArea jtaItems;
	public javax.swing.JTextField txtDataset;
	// End of variables declaration//GEN-END:variables

}